services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "tabnews"
    ports:
      - "5432:5432"
